[package]
name = "coho_nft"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[dependencies]
cosmwasm-std = { version = "1.0.0" }
cw721 = { version = "0.13.2" }
schemars = "0.8.10"
serde = { version = "1.0.137", default-features = false, features = ["derive"] }
